attendance/urls.py
from django.urls import path

from attendance import attendance_views

app_name = 'attendance'

urlpatterns = [
    path('', attendance_views.attendance_list, name='attendance_list')
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from ias.views import base_views

urlpatterns = [
    path('ias/', include('ias.urls')),
    path('common/', include('common.urls')),
    path('admin/', admin.site.urls),
    path('', base_views.ai_index, name='ai_index'),
    path('attendance', include('attendance.urls')),
    path('discussion/', include('discussion.urls')),
    path('transcribe-audio/', include('voice.urls'))
]

ias/urls.py
from django.urls import path

from .views import base_views, input_views, ai_views

app_name = 'ias'

urlpatterns = [
    # base_views.py
    path('',
         base_views.ai_index, name='ai_index'),
    path('<int:ai_id>/',
         base_views.ai_detail, name='ai_detail'),

    # ai_views.py
    path('ai/create/',
         ai_views.ai_create, name='ai_create'),

    # input_views.py
    # path('input/create/<int:ai_id>/',
    #      input_views.input_create, name='input_create'),
    path('input/modify/<int:input_id>/',
         input_views.input_modify, name='input_modify'),
    path('input/delete/<int:input_id>/',
         input_views.input_delete, name='input_delete'),
    path('input/vote/<int:input_id>/', input_views.input_vote, name='input_vote'),

]

ias/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from ..function.inputBlock import get_recent_week
from ..models import AI


def ai_index(request):
    page = request.GET.get('page', 1) # 페이지
    kw = request.GET.get('kw', '') # 검색어
    ai_list = AI.objects.order_by('-create_date')
    if kw:
        ai_list = ai_list.filter(
            Q(engSubject__icontains=kw) | # 제목 검색
            Q(engContent__icontains=kw)   # 내용 검색
        ).distinct()
    paginator = Paginator(ai_list, 10) # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'ai_list': page_obj,  'page': page, 'kw': kw}

    return render(request, 'ias/ai_list.html', context)



def ai_detail(request, ai_id):
    ai = get_object_or_404(AI, pk=ai_id)
    recentWeek = get_recent_week()
    print('recentWeek: ' + str(recentWeek))
    context = {'ai': ai, 'recentWeek': recentWeek}
    return render(request, 'ias/ai_detail.html', context)

templates/base.html
{% load static %}
<html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>IT Article Study</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'ias:ai_index' %}">IT Article Study</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (Logout)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">Login</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">Sign Up</a>
                    {% endif %}
                </li>
                <li>
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'attendance:attendance_list' %}">Attendance</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>