attendance/urls.py
from django.urls import path

from attendance import attendance_views

app_name = 'attendance'

urlpatterns = [
    path('', attendance_views.attendance_list, name='attendance_list')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from ias.views import base_views

urlpatterns = [
    path('ias/', include('ias.urls')),
    path('common/', include('common.urls')),
    path('admin/', admin.site.urls),
    path('', base_views.ai_index, name='ai_index'),
    path('attendance', include('attendance.urls')),
    path('discussion/', include('discussion.urls')),
    path('transcribe-audio/', include('voice.urls'))
]

ias/urls.py
from django.urls import path

from .views import base_views, input_views, ai_views

app_name = 'ias'

urlpatterns = [
    # base_views.py
    path('',
         base_views.ai_index, name='ai_index'),
    path('<int:ai_id>/',
         base_views.ai_detail, name='ai_detail'),

    # ai_views.py
    path('ai/create/',
         ai_views.ai_create, name='ai_create'),

    # input_views.py
    # path('input/create/<int:ai_id>/',
    #      input_views.input_create, name='input_create'),
    path('input/modify/<int:input_id>/',
         input_views.input_modify, name='input_modify'),
    path('input/delete/<int:input_id>/',
         input_views.input_delete, name='input_delete'),
    path('input/vote/<int:input_id>/', input_views.input_vote, name='input_vote'),

]

attendance/models.py
from django.contrib.auth.models import User
from django.db import models

from ias.models import AI

class Attendance(models.Model):
    week = models.IntegerField(null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    attended = models.BooleanField(null=True)
    due_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"Week {self.week} - {self.user}"

templates/attendance/attendance_list.html
{% extends 'base.html' %}
{% load ias_filter %}

{% block content %}
<div class="container">
     <h1>Attendance List</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Week</th>
                <th>Article</th>
                <th>Due Date</th>
                {% for user in users %}
                <th>{{ user }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
        {% if page_obj %}
            {% for attendance in page_obj %}
            <tr>
                <td>{{ attendance.0 }}</td>
                <td><a href="{% url 'ias:ai_detail' attendance.0 %}">{{ attendance.1 }}</a></td>
                <td>{{ attendance.2|add_days:7 }}</td>
                {% for hit in attendance.4 %}
                <td>
                    {% if hit == 0 or hit is None %}
                        <t>X</t>
                    {% else %}
                        {% if hit > 60 %}
                            <span style="color: green">{{ hit }}%</span>
                        {% else %}
                            <span style="color: red">{{ hit }}%</span>
                        {% endif %}
                    {% endif %}
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="4">There's no Attendance.</td>
            </tr>
        {% endif %}

        </tbody>
    </table>

    <!-- Pagination links -->
     <div class="pagination justify-content-center">
         <span class="step-links">
             {% if page_obj.has_previous %}
                 <a href="?page=1">&laquo; first</a>
                 <a href="?page={{ page_obj.previous_page_number }}">previous</a>
             {% endif %}

             <span class="current">
                 Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
             </span>

             {% if page_obj.has_next %}
                 <a href="?page={{ page_obj.next_page_number }}">next</a>
                 <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
             {% endif %}
         </span>
     </div>
 </div>

</div>


{% endblock %}

{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // Start from page 1 when searching
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}